Added accuracy validation for CPP part
openvinotoolkit/model_api pull request #26
Opened 2023-03-07 08:18 UTC by AlexKoff88

2023-03-07 14:00 UTC, Wovchena requested changes

2023-03-08 06:05 UTC, AlexKoff88 commented
I've supported ClassificationModels as well. Current tests show that the results diverge for Python and C++ API.

2023-03-08 08:52 UTC, Wovchena commented
I will look into it

2023-03-08 08:57 UTC, Wovchena approved these changes
Ok

2023-03-08 09:07 UTC, merged