[Draft]: Updated README with the list of supported models
openvinotoolkit/model_api pull request #31
Opened 2023-03-09 09:15 UTC by AlexKoff88

2023-03-09 09:22 UTC, Wovchena requested changes

2023-03-09 09:22 UTC, Wovchena commented on README.md
> +Model API stores additional information required for model inference, data, pre/postprocessing, label names, etc. directly in OpenVINO Intermediate Representation. This information is used to prepare
```suggestion
Model API searches for additional information required for model inference, data, pre/postprocessing, label names, etc. directly in OpenVINO Intermediate Representation. This information is used to prepare the inference data, process and ouput the inference results in a human-readable format.
```
ModelAPI doesn't generate IR in all cases thus it doesn't store anything

2023-03-09 09:22 UTC, Wovchena commented on README.md
> +  - Any model converted to OpenVION IR format
```suggestion
```
`Any model converted to OpenVION IR format` is a very general statement. Maybe we could just not specify it at all

2023-03-15 05:58 UTC, AlexKoff88 commented
Avoid generic statements about the supported models.

2023-03-17 12:41 UTC, merged