Add python version of tilers
openvinotoolkit/model_api pull request #93
Opened 2023-06-26 17:56 UTC by sovrasov

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2023-07-03 09:04 UTC, sovrasov commented
@Wovchena please have a look at python stuff. IS tiler is not fully finished (XAI is lacking). Also, tests are missing.

2023-07-03 11:21 UTC, Wovchena requested changes
All in all the design looks good

2023-07-03 11:21 UTC, Wovchena commented on model_api/python/openvino/model_api/tilers/instance_segmentation.py
> +            if len(result["bboxes"]):
This should probably be
```suggestion
            if len(result["masks"]):
```

2023-07-03 12:29 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/detection.py
> +            np.average(feature_vectors, axis=0) if feature_vectors else np.ndarray(0)
Right now there is no reason, probably, during the original experiments, weighting of features was used.

2023-07-03 15:16 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/detection.py
> +        output_dict["tile_coords"] = meta["coord"]
There was a mistake in _predict_sync, meta should always be a dict

2023-07-03 15:19 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/detection.py
> +                y_2, x_2 = ((y_2, x_2) * ratio).astype(np.uint16)
Updated to use pure python

2023-07-03 15:27 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/tiler.py
> +        """Tiles an input image to either overlapping, non-overlapping or random patches.
Updated

2023-07-03 15:27 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/tiler.py
> +        By default, this method also adds the full image as the first tile to process.
Updated

2023-07-03 15:28 UTC, Wovchena commented on model_api/python/openvino/model_api/tilers/detection.py
> +        output_dict["tile_coords"] = meta["coord"]
Now you always pass `coord`. It makes sense to make it ordinary function arg.

2023-07-03 15:28 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/tiler.py
> +    def _merge_results(self, results, shapem, meta=None):
Actually, it called in this way in IS tiler to save nms keep indices to meta. I'll try to split IS and detection implementations.

2023-07-04 16:59 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/instance_segmentation.py
> +            if len(result["bboxes"]):
Fixed

2023-07-04 16:59 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/detection.py
> +        output_dict["tile_coords"] = meta["coord"]
Changed

2023-07-04 17:00 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/tiler.py
> +    def _merge_results(self, results, shapem, meta=None):
Changed, now IS tiler doesn't need that

2023-07-05 09:54 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/detection.py
> +                        merged_map[class_idx][y_1 + hi, x_1 + wi] = 0.5 * (map_pixel + merged_pixel)
Yes, that's a heuristic for merging. Max looks more natural, but during the initial experiments it produced more artifacts. I'll have a look at this one more time.

2023-07-05 09:55 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/detection.py
> +            detections = _detection2array(predictions)
Updated

2023-07-05 10:22 UTC, Wovchena commented on model_api/python/openvino/model_api/tilers/tiler.py
> +    def _merge_results(self, results, shapem, meta=None):
I can't find any call of `_merge_results()` with non default `meta`. Should `meta` be removed now as it is always `None`?

2023-07-07 10:00 UTC, Wovchena approved these changes

2023-07-07 10:00 UTC, Wovchena commented on model_api/python/openvino/model_api/tilers/__init__.py
Should I merge this PR now?

2023-07-07 10:18 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/__init__.py
Yes, it's ready for merge. I'm working on cpp part in another branch

2023-07-07 10:18 UTC, sovrasov commented on tests/python/accuracy/test_accuracy.py
> +            image = cv2.resize(image, eval(model_data["input_res"]))
The model was trained on that data and retrieves a very long list of detections, so the resulting json gets overwhelmed.

2023-07-07 10:26 UTC, sovrasov commented on model_api/python/openvino/model_api/tilers/instance_segmentation.py
> +            masks = [masks[keep_idx] for keep_idx in keep_idxs]
Removed that check

2023-07-07 11:18 UTC, merged